default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hegedb
  username: hege
  password: Dweller-Stoplight-Clamor5
  host: grogu.ddns.net
  port: 5432

test:
  <<: *default
  database: hegedb
  username: hege
  password: Dweller-Stoplight-Clamor5
  host: grogu.ddns.net
  port: 5432

production:
  <<: *default
  database: hegedb
  username: hege
  password: Dweller-Stoplight-Clamor5
  host: grogu.ddns.net
  port: 5432
